apiVersion: v1
kind: ConfigMap
metadata:
  name: orderflow-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5433/orderflow"
  KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:29092"