CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    quantity INTEGER NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL
);


CREATE TABLE outbox_events (
    id VARCHAR(255) PRIMARY KEY,
    aggregate_id BIGINT NOT NULL,
    aggregate_type VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    last_attempt_at TIMESTAMPTZ,
    processing_started_at TIMESTAMPTZ,
    status VARCHAR(255) NOT NULL,
    retry_count INTEGER NOT NULL,
    next_attempt_at TIMESTAMPTZ NOT NULL
);


CREATE TABLE processed_events (
    event_id VARCHAR(255) PRIMARY KEY,
    processed_at TIMESTAMPTZ NOT NULL
);


CREATE TABLE failed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    event_id VARCHAR(255) NOT NULL,
    exception_class VARCHAR(255),
    exception_message TEXT,
    last_replayed_at TIMESTAMPTZ,
    original_key VARCHAR(255),
    original_offset BIGINT NOT NULL,
    original_partition INTEGER NOT NULL,
    original_topic VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    replay_count INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,

    CONSTRAINT uk_failed_event_original_record
        UNIQUE (original_topic, original_partition, original_offset),

    CONSTRAINT failed_events_status_check
        CHECK (
            status IN (
                'FAILED',
                'REPLAYED',
                'RESOLVED'
            )
        )
);


CREATE INDEX idx_failed_events_event_id
    ON failed_events(event_id);


CREATE INDEX idx_failed_events_status
    ON failed_events(status);
