name: OrderFlow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:17

        env:
          POSTGRES_DB: orderflow
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin

        ports:
          - 5433:5432

        options: >-
          --health-cmd="pg_isready -U postgres -d orderflow"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


      kafka:
        image: apache/kafka:4.1.2

        ports:
          - 9092:9092

        env:
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller

          KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven


      - name: Wait for Kafka
        run: |
          echo "Waiting for Kafka on localhost:9092..."

          for i in {1..30}; do
            if nc -z localhost 9092; then
              echo "Kafka port is available"
              exit 0
            fi

            echo "Kafka not ready yet..."
            sleep 2
          done

          echo "Kafka did not start"
          exit 1


      - name: Create Kafka topics
        run: |
          docker exec ${{ job.services.kafka.id }} \
            /opt/kafka/bin/kafka-topics.sh \
            --bootstrap-server localhost:9092 \
            --create \
            --if-not-exists \
            --topic order-events \
            --partitions 3 \
            --replication-factor 1

          docker exec ${{ job.services.kafka.id }} \
            /opt/kafka/bin/kafka-topics.sh \
            --bootstrap-server localhost:9092 \
            --create \
            --if-not-exists \
            --topic order-events.DLT \
            --partitions 3 \
            --replication-factor 1

          docker exec ${{ job.services.kafka.id }} \
            /opt/kafka/bin/kafka-topics.sh \
            --bootstrap-server localhost:9092 \
            --describe \
            --topic order-events

          docker exec ${{ job.services.kafka.id }} \
            /opt/kafka/bin/kafka-topics.sh \
            --bootstrap-server localhost:9092 \
            --describe \
            --topic order-events.DLT

      - name: Build and test
        run: ./mvnw clean test -DforkCount=1 -DreuseForks=true
